import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { AlertTriangle, CheckCircle2, Plus, RotateCcw } from 'lucide-react';
import { Button, Card, PageHead, PrintButton, Sheet, Tabs } from './components';
import { money, uid } from './store';
import type { Column, Row } from './types';

export type ERPContext={rows:Record<string,Row[]>;setRows:(x:Record<string,Row[]>)=>void;go:(s:any)=>void};
const n=(v:unknown)=>Number(v)||0;
const today=()=>new Date().toISOString().slice(0,10);
const lineTotal=(r:Row)=>n(r.quantity)*n(r.price);
const allStock=(rows:Record<string,Row[]>):Row[]=>['wood','iron','paint','accessories','aluminum','workshop'].flatMap(k=>(rows[k]||[]).map(x=>({...x,section:k}) as Row));

function NestedLines({ctx,parentId,keyName,mode}:{ctx:ERPContext;parentId:string;keyName:string;mode:'sale'|'purchase'|'manufacturing'}){
 const items=(ctx.rows[keyName]||[]).filter(x=>x.parentId===parentId), products=ctx.rows.products||[], stock=allStock(ctx.rows);
 const source=mode==='sale'?products:stock;
 const cols:Column[]=[{key:'item',label:'المادة / المنتج',type:'select',options:source.map(x=>String(x.name)).filter(Boolean),width:180},{key:'quantity',label:'الكمية',type:'number'},{key:'unit',label:'الوحدة',type:'select',options:['قطعة','متر','متر مكعب','كجم','جم','لتر','جالون']},{key:'length',label:'الطول',type:'number'},{key:'width',label:'العرض',type:'number'},{key:'thickness',label:'التخانة',type:'number'},{key:'priceMode',label:'نظام السعر',type:'select',options:['سعر الشراء','سعر البيع']},{key:'price',label:'سعر الوحدة',type:'number'},{key:'total',label:'الإجمالي',calc:r=>money(lineTotal(r))}];
 const update=(next:Row[])=>ctx.setRows({...ctx.rows,[keyName]:[...(ctx.rows[keyName]||[]).filter(x=>x.parentId!==parentId),...next]});
 const add=()=>update([...items,{id:uid(),parentId,quantity:1,unit:'قطعة',priceMode:mode==='sale'?'سعر البيع':'سعر الشراء'}]);
 return <div className="nested-panel"><div className="nested-head"><div><b>{mode==='manufacturing'?'الخامات المطلوبة':'بنود المستند'}</b><span>أدخل البنود مباشرة؛ الإجمالي يتحدث فوراً</span></div><strong>{money(items.reduce((s,x)=>s+lineTotal(x),0))}</strong></div><Sheet columns={cols} rows={items} onChange={next=>{const enriched=next.map(line=>{const found=source.find(x=>x.name===line.item);if(found&&(!line.price||line.item!==items.find(i=>i.id===line.id)?.item)){return {...line,unit:found.unit||line.unit,price:line.priceMode==='سعر البيع'?n(found.sell||found.sale):n(found.buy)}}return line});update(enriched)}} onAdd={add} addLabel="إضافة بند" onDelete={id=>update(items.filter(x=>x.id!==id))}/></div>
}

function journal(rows:Record<string,Row[]>,entry:Partial<Row>){return [{id:uid(),date:today(),locked:true,...entry},...(rows.journal||[])]}
function adjustStock(rows:Record<string,Row[]>,item:string,delta:number){const out={...rows};for(const key of ['wood','iron','paint','accessories','aluminum','workshop'])out[key]=(out[key]||[]).map(r=>r.name===item?{...r,count:n(r.count)+delta,quantity:n(r.quantity)+delta}:r);out.products=(out.products||[]).map(r=>r.name===item?{...r,stock:n(r.stock)+delta}:r);return out}

export function AdvancedOrders({kind,...ctx}:ERPContext&{kind:'manufacturing'|'purchases'}){
 const manufacturing=kind==='manufacturing', lineKey=manufacturing?'manufacturingLines':'purchaseLines';
 const cols:Column[]=manufacturing?[{key:'number',label:'رقم الأمر'},{key:'customer',label:'العميل',type:'select',options:(ctx.rows.customers||[]).map(x=>String(x.name))},{key:'product',label:'المنتج',type:'select',options:(ctx.rows.products||[]).filter(x=>x.kind==='منتج تصنيعي').map(x=>String(x.name))},{key:'quantity',label:'الكمية',type:'number'},{key:'labor',label:'العمالة',type:'number'},{key:'profit',label:'المكسب',type:'number'},{key:'delivery',label:'التسليم',type:'date'},{key:'status',label:'الحالة',type:'status',options:['قيد التصنيع','مكتمل']},{key:'total',label:'السعر النهائي',calc:r=>money(totalFor(ctx.rows,lineKey,r.id)+n(r.labor)+n(r.profit))}]:[{key:'number',label:'رقم الأمر'},{key:'supplier',label:'المورد',type:'select',options:(ctx.rows.suppliers||[]).map(x=>String(x.name))},{key:'date',label:'تاريخ الطلب',type:'date'},{key:'receive',label:'الاستلام المتوقع',type:'date'},{key:'status',label:'الحالة',type:'status',options:['قيد الطلب','تم الاستلام']},{key:'total',label:'الإجمالي',calc:r=>money(totalFor(ctx.rows,lineKey,r.id))}];
 const update=(next:Row[])=>{let data={...ctx.rows,[kind]:next};for(const row of next){const old=(ctx.rows[kind]||[]).find(x=>x.id===row.id);const completed=manufacturing?row.status==='مكتمل'&&old?.status!=='مكتمل':row.status==='تم الاستلام'&&old?.status!=='تم الاستلام';if(!completed)continue;const lines=(ctx.rows[lineKey]||[]).filter(x=>x.parentId===row.id),total=lines.reduce((s,x)=>s+lineTotal(x),0)+n(row.labor)+n(row.profit);if(manufacturing){for(const l of lines)data=adjustStock(data,String(l.item),-n(l.quantity));data=adjustStock(data,String(row.product),n(row.quantity));const invoice={id:uid(),number:`SI-${String((data.sales||[]).length+1).padStart(4,'0')}`,customer:row.customer,date:today(),status:'مكتملة',source:row.number,total};data.sales=[invoice,...(data.sales||[])];data.journal=journal(data,{type:'فاتورة بيع',description:`فاتورة ناتجة عن أمر التصنيع ${row.number}`,amount:total,side:'دائن',party:row.customer});}else{for(const l of lines)data=adjustStock(data,String(l.item),n(l.quantity));const invoice={id:uid(),number:`PI-${String((data.purchaseInvoices||[]).length+1).padStart(4,'0')}`,supplier:row.supplier,date:today(),status:'مكتملة',source:row.number,total};data.purchaseInvoices=[invoice,...(data.purchaseInvoices||[])];data.journal=journal(data,{type:'فاتورة شراء',description:`فاتورة ناتجة عن أمر الشراء ${row.number}`,amount:total,side:'مدين',party:row.supplier});}}ctx.setRows(data)};
 const add=()=>ctx.setRows({...ctx.rows,[kind]:[{id:uid(),number:`${manufacturing?'MO':'PO'}-${String((ctx.rows[kind]||[]).length+1).padStart(4,'0')}`,date:today(),status:manufacturing?'قيد التصنيع':'قيد الطلب'},...(ctx.rows[kind]||[])]});
 return <><PageHead title={manufacturing?'أوامر التصنيع':'أوامر الشراء'} desc={manufacturing?'المواد والعمالة والتسليم مع خصم المخزون وإنشاء الفاتورة تلقائياً':'بنود المورد والاستلام مع زيادة المخزون وإنشاء فاتورة الشراء'} action={<Button onClick={add}><Plus/>إضافة أمر</Button>}/><Card className="automation-note"><CheckCircle2/><div><b>الربط التلقائي مفعّل</b><span>{manufacturing?'عند الإكمال: تُخصم الخامات ويُضاف المنتج وتُنشأ فاتورة بيع وقيد':'عند الاستلام: تزداد الكميات وتُنشأ فاتورة شراء وقيد'}</span></div></Card><Sheet columns={cols} rows={ctx.rows[kind]||[]} onChange={update} onDelete={id=>ctx.setRows({...ctx.rows,[kind]:(ctx.rows[kind]||[]).filter(x=>x.id!==id)})} expanded={r=><NestedLines ctx={ctx} parentId={r.id} keyName={lineKey} mode={manufacturing?'manufacturing':'purchase'}/>}/></>
}
const totalFor=(rows:Record<string,Row[]>,key:string,parentId:string)=>(rows[key]||[]).filter(x=>x.parentId===parentId).reduce((s,x)=>s+lineTotal(x),0);

export function AdvancedInvoices({kind,...ctx}:ERPContext&{kind:'sales'|'purchaseInvoices'}){
 const sale=kind==='sales',lineKey=sale?'salesLines':'purchaseInvoiceLines', [returnFor,setReturnFor]=useState('');
 const cols:Column[]=[{key:'number',label:'رقم الفاتورة'},{key:sale?'customer':'supplier',label:sale?'العميل':'المورد',type:'select',options:(ctx.rows[sale?'customers':'suppliers']||[]).map(x=>String(x.name))},{key:'date',label:'التاريخ',type:'date'},{key:'discountType',label:'نوع الخصم',type:'select',options:['مبلغ','نسبة %']},{key:'discount',label:'الخصم',type:'number'},...(sale?[{key:'payment',label:'طريقة الدفع',type:'select' as const,options:['كاش','تقسيط','تحويل']}]:[]),{key:'status',label:'الحالة',type:'status',options:['مسودة','مكتملة']},{key:'total',label:'الإجمالي',calc:r=>money(invoiceTotal(ctx.rows,lineKey,r))}];
 const update=(next:Row[])=>{let data={...ctx.rows,[kind]:next};for(const r of next){const old=(ctx.rows[kind]||[]).find(x=>x.id===r.id);if(r.status!=='مكتملة'||old?.status==='مكتملة')continue;const lines=(ctx.rows[lineKey]||[]).filter(x=>x.parentId===r.id);for(const l of lines)data=adjustStock(data,String(l.item),sale?-n(l.quantity):n(l.quantity));const total=invoiceTotal(data,lineKey,r);data.journal=journal(data,{type:sale?'فاتورة بيع':'فاتورة شراء',description:`${sale?'بيع':'شراء'} مباشر - ${r.number}`,amount:total,side:sale?'دائن':'مدين',party:r[sale?'customer':'supplier']});}ctx.setRows(data)};
 const add=()=>ctx.setRows({...ctx.rows,[kind]:[{id:uid(),number:`${sale?'SI':'PI'}-${String((ctx.rows[kind]||[]).length+1).padStart(4,'0')}`,date:today(),status:'مسودة',discountType:'مبلغ'},...(ctx.rows[kind]||[])]});
 return <><PageHead title={sale?'فواتير البيع':'فواتير الشراء'} desc="فواتير متعددة البنود مرتبطة بالمخزون والقيود اليومية" action={<div className="head-actions"><PrintButton/><Button onClick={add}><Plus/>إنشاء فاتورة</Button></div>}/><Sheet columns={cols} rows={ctx.rows[kind]||[]} onChange={update} onDelete={id=>ctx.setRows({...ctx.rows,[kind]:(ctx.rows[kind]||[]).filter(x=>x.id!==id)})} expanded={r=><div><NestedLines ctx={ctx} parentId={r.id} keyName={lineKey} mode={sale?'sale':'purchase'}/>{sale&&<div className="return-box"><Button variant="outline" onClick={()=>setReturnFor(returnFor===r.id?'':r.id)}><RotateCcw/>إنشاء مرتجع</Button>{returnFor===r.id&&<ReturnForm ctx={ctx} invoice={r}/>}</div>}</div>}/></>
}
function invoiceTotal(rows:Record<string,Row[]>,key:string,r:Row){const sub=totalFor(rows,key,r.id),d=n(r.discount);return Math.max(0,r.discountType==='نسبة %'?sub*(1-d/100):sub-d)}
function ReturnForm({ctx,invoice}:{ctx:ERPContext;invoice:Row}){const schema=z.object({item:z.string().min(1,'اختر المنتج'),quantity:z.number().positive('الكمية مطلوبة'),amount:z.number().nonnegative()});type Form=z.infer<typeof schema>;const {register,handleSubmit,formState:{errors},reset}=useForm<Form>({resolver:zodResolver(schema)});const submit=(v:Form)=>{let data=adjustStock(ctx.rows,v.item,v.quantity);data.returns=[{id:uid(),invoiceId:invoice.id,date:today(),...v},...(data.returns||[])];data.journal=journal(data,{type:'مرتجع بيع',description:`مرتجع من الفاتورة ${invoice.number}`,amount:v.amount,side:'مدين',party:invoice.customer});ctx.setRows(data);reset()};return <form className="inline-form" onSubmit={handleSubmit(submit)}><label>المنتج<select {...register('item')}><option value="">اختر</option>{(ctx.rows.products||[]).map(x=><option key={x.id}>{String(x.name)}</option>)}</select>{errors.item&&<small>{errors.item.message}</small>}</label><label>الكمية<input type="number" {...register('quantity',{valueAsNumber:true})}/></label><label>قيمة المرتجع<input type="number" {...register('amount',{valueAsNumber:true})}/></label><Button type="submit">تأكيد المرتجع</Button></form>}

export function ValidatedPeople({kind,...ctx}:ERPContext&{kind:'customers'|'suppliers'}){
 const customer=kind==='customers',[adding,setAdding]=useState(false);const schema=z.object({name:z.string().min(2,'الاسم مطلوب'),phone:z.string().min(8,'رقم الهاتف مطلوب'),city:z.string().min(1,'اختر المدينة'),address:z.string().optional()});type Form=z.infer<typeof schema>;const {register,handleSubmit,reset,formState:{errors}}=useForm<Form>({resolver:zodResolver(schema)});const submit=(v:Form)=>{ctx.setRows({...ctx.rows,[kind]:[{id:uid(),...v,balance:0,total:0},...(ctx.rows[kind]||[])]});reset();setAdding(false)};const cols:Column[]=[{key:'name',label:customer?'الاسم الكامل':'اسم المورد'},{key:'phone',label:'الهاتف'},{key:'city',label:'المدينة'},{key:'address',label:'العنوان'},...(customer?[{key:'phone2',label:'هاتف إضافي'},{key:'credit',label:'حد الائتمان',type:'number' as const}]:[{key:'materials',label:'المواد الموردة',type:'select' as const,options:['خشب','حديد','دهانات','ألومنيوم','إكسسوارات','مستلزمات ورشة','أخرى']}]),{key:'balance',label:'الرصيد',calc:r=>money(r.balance as number)},{key:'total',label:'إجمالي التعاملات',calc:r=>money(r.total as number)}];return <><PageHead title={customer?'العملاء':'الموردون'} desc="بيانات الاتصال والأرصدة وسجل الفواتير والمدفوعات" action={<Button onClick={()=>setAdding(!adding)}><Plus/>إضافة {customer?'عميل':'مورد'}</Button>}/>{adding&&<Card><form className="entity-form" onSubmit={handleSubmit(submit)}><label>الاسم<input {...register('name')}/><small>{errors.name?.message}</small></label><label>الهاتف<input {...register('phone')}/><small>{errors.phone?.message}</small></label><label>المدينة<select {...register('city')}><option value="">اختر</option>{['القاهرة','الجيزة','الإسكندرية','القليوبية','الشرقية','الدقهلية','الغربية','المنوفية','البحيرة'].map(x=><option key={x}>{x}</option>)}</select><small>{errors.city?.message}</small></label><label>العنوان<input {...register('address')}/></label><Button type="submit">إضافة</Button></form></Card>}<Sheet columns={cols} rows={ctx.rows[kind]||[]} onChange={v=>ctx.setRows({...ctx.rows,[kind]:v})} onDelete={id=>ctx.setRows({...ctx.rows,[kind]:(ctx.rows[kind]||[]).filter(x=>x.id!==id)})} expanded={r=><div className="history-grid">{['الرصيد الحالي','إجمالي التعاملات','الفواتير','المدفوعات'].map(x=><div key={x}><span>{x}</span><b>{x==='الفواتير'?String((ctx.rows[customer?'sales':'purchaseInvoices']||[]).filter(i=>i[customer?'customer':'supplier']===r.name).length):money(Number(x==='الرصيد الحالي'?r.balance:r.total))}</b></div>)}</div>}/></>}
