import { AlertTriangle, BarChart3, Bell, CircleDollarSign, Clock3, Factory, Plus, TrendingUp, WalletCards } from 'lucide-react';
import { Button, Card, PageHead, Sheet } from './components';
import { money, uid } from './store';
import type { Column, Row } from './types';
import type { ERPContext } from './advanced';
const n=(v:unknown)=>Number(v)||0;
const today=()=>new Date().toISOString().slice(0,10);
function changeStock(rows:Record<string,Row[]>,item:string,delta:number){const out={...rows};for(const k of ['wood','iron','paint','accessories','aluminum','workshop'])out[k]=(out[k]||[]).map(r=>r.name===item?{...r,count:n(r.count)+delta,quantity:n(r.quantity)+delta}:r);out.products=(out.products||[]).map(r=>r.name===item?{...r,stock:n(r.stock)+delta}:r);return out}
const addJournal=(rows:Record<string,Row[]>,e:Partial<Row>)=>[{id:uid(),date:today(),locked:true,...e},...(rows.journal||[])];
const stockNames=(rows:Record<string,Row[]>)=>[...(rows.products||[]),...['wood','iron','paint','accessories','aluminum','workshop'].flatMap(k=>rows[k]||[])].map(x=>String(x.name)).filter(Boolean);

export function AdvancedWaste(ctx:ERPContext){const cols:Column[]=[{key:'item',label:'المنتج / المادة',type:'select',options:stockNames(ctx.rows)},{key:'quantity',label:'الكمية',type:'number'},{key:'price',label:'السعر',type:'number'},{key:'reason',label:'سبب التلف',type:'select',options:['كسر','عيب صناعة','تخزين','رطوبة','أخرى']},{key:'date',label:'التاريخ',type:'date'},{key:'status',label:'الحالة',type:'status',options:['مسودة','تم التسجيل']},{key:'loss',label:'إجمالي الخسارة',calc:r=>money(n(r.quantity)*n(r.price))}];const update=(next:Row[])=>{let data:Record<string,Row[]>={...ctx.rows,waste:next};for(const r of next){const old=(ctx.rows.waste||[]).find(x=>x.id===r.id);if(r.status==='تم التسجيل'&&old?.status!=='تم التسجيل'){data=changeStock(data,String(r.item),-n(r.quantity));data.journal=addJournal(data,{type:'تالف',description:`تالف: ${r.item} - ${r.reason}`,amount:n(r.quantity)*n(r.price),side:'مدين'});}}ctx.setRows(data)};return <><PageHead title="التوالف" desc="خصم فوري من المخزن وتسجيل الخسارة في القيود والتقارير" action={<Button onClick={()=>ctx.setRows({...ctx.rows,waste:[{id:uid(),date:today(),status:'مسودة'},...(ctx.rows.waste||[])]})}><Plus/>إضافة تالف</Button>}/><Card className="automation-note"><AlertTriangle/><div><b>عند اختيار «تم التسجيل»</b><span>تُخصم الكمية ويُنشأ قيد خسارة تلقائياً</span></div></Card><Sheet columns={cols} rows={ctx.rows.waste||[]} onChange={update} onDelete={id=>ctx.setRows({...ctx.rows,waste:(ctx.rows.waste||[]).filter(x=>x.id!==id)})}/></>}

export function AdvancedSurplus(ctx:ERPContext){const cols:Column[]=[{key:'order',label:'أمر التصنيع',type:'select',options:(ctx.rows.manufacturing||[]).map(x=>String(x.number))},{key:'material',label:'المادة',type:'select',options:stockNames(ctx.rows)},{key:'quantity',label:'الكمية',type:'number'},{key:'length',label:'الطول',type:'number'},{key:'width',label:'العرض',type:'number'},{key:'thickness',label:'التخانة',type:'number'},{key:'usable',label:'صالح للاستخدام؟',type:'select',options:['نعم','لا']},{key:'status',label:'الإجراء',calc:r=>r.processed?r.usable==='نعم'?'عاد للمخزن':'تحول للتوالف':'بانتظار الإكمال'}];const update=(next:Row[])=>{let data:Record<string,Row[]>={...ctx.rows,surplus:next};for(const r of next){const old=(ctx.rows.surplus||[]).find(x=>x.id===r.id);if(r.usable&&!r.processed&&!old?.processed){if(r.usable==='نعم')data=changeStock(data,String(r.material),n(r.quantity));else{data.waste=[{id:uid(),item:r.material,quantity:r.quantity,price:r.price||0,reason:'زيادة غير صالحة',date:today(),status:'تم التسجيل'},...(data.waste||[])];data.journal=addJournal(data,{type:'تالف',description:`زيادة غير صالحة من ${r.order}`,amount:n(r.quantity)*n(r.price),side:'مدين'});}data.surplus=(data.surplus||[]).map(x=>x.id===r.id?{...x,processed:true}:x);}}ctx.setRows(data)};return <><PageHead title="زيادات الأوردرات" desc="إرجاع الزيادات الصالحة للمخزن وتحويل غير الصالح إلى التوالف" action={<Button onClick={()=>ctx.setRows({...ctx.rows,surplus:[{id:uid()},...(ctx.rows.surplus||[])]})}><Plus/>إضافة زيادة</Button>}/><Sheet columns={cols} rows={ctx.rows.surplus||[]} onChange={update} onDelete={id=>ctx.setRows({...ctx.rows,surplus:(ctx.rows.surplus||[]).filter(x=>x.id!==id)})}/></>}

export function AdvancedDashboard({rows,go}:ERPContext){const saleTotal=(rows.sales||[]).filter(x=>x.date===today()).reduce((s,x)=>s+n(x.total),0),open=(rows.manufacturing||[]).filter(x=>x.status!=='مكتمل').length,late=(rows.manufacturing||[]).filter(x=>x.status!=='مكتمل'&&String(x.delivery)<today()).length,credits=(rows.journal||[]).filter(x=>x.side==='دائن').reduce((s,x)=>s+n(x.amount),0),debits=(rows.journal||[]).filter(x=>x.side==='مدين').reduce((s,x)=>s+n(x.amount),0),profit=credits-debits;const cards=[['مبيعات اليوم',money(saleTotal),CircleDollarSign,'green'],['أوامر تصنيع مفتوحة',open,Factory,'blue'],['مواعيد تسليم متأخرة',late,Clock3,'red'],['المبلغ في الخزنة',money(profit),WalletCards,'purple'],['صافي الربح',money(profit),TrendingUp,'amber']];const low=['wood','iron','paint','accessories','aluminum'].flatMap(k=>rows[k]||[]).filter(x=>n(x.count||x.quantity)<=n(x.min||2));return <><div className="dash-title"><div><span className="eyebrow">نظرة عامة لحظية</span><h1>El Ayad Furniture</h1><p>الأرقام محسوبة من الحركات المسجلة في النظام.</p></div><div className="today">{today()}</div></div><div className="stats">{cards.map(([l,v,I,t]:any)=><Card className="stat" key={l}><div className={`stat-icon ${t}`}><I/></div><div><span>{l}</span><strong>{v}</strong><small>تحديث تلقائي</small></div></Card>)}</div><div className="dash-grid"><Card className="chart-card"><div className="card-title"><div><h3>المبيعات الشهرية</h3><p>تجميع تلقائي حسب الشهر</p></div></div><div className="chart css-chart">{['يناير','فبراير','مارس','أبريل','مايو','يونيو'].map((m,i)=><div key={m}><span className="bar" style={{height:`${Math.max(3,(rows.sales||[]).length*(i+1)*2)}%`}}/><small>{m}</small></div>)}</div></Card><Card className="alerts"><div className="card-title"><div><h3>تنبيهات سريعة</h3><p>عناصر تحتاج إلى الانتباه</p></div></div><div className="alert-list"><div><AlertTriangle/><span>خامات قاربت على النفاد</span><b>{low.length}</b></div><div><Clock3/><span>أوامر متأخرة</span><b>{late}</b></div><div><Bell/><span>عملاء عليهم مستحقات</span><b>{(rows.customers||[]).filter(x=>n(x.balance)>0).length}</b></div></div></Card></div><div className="dash-grid bottom"><Card><div className="card-title"><h3>آخر 5 فواتير بيع</h3><Button variant="ghost" onClick={()=>go('sales')}>عرض الكل</Button></div><Mini rows={(rows.sales||[]).slice(0,5)} name="number"/></Card><Card><div className="card-title"><h3>آخر 5 أوامر تصنيع</h3><Button variant="ghost" onClick={()=>go('manufacturing')}>عرض الكل</Button></div><Mini rows={(rows.manufacturing||[]).slice(0,5)} name="number"/></Card></div></>}
function Mini({rows,name}:{rows:Row[];name:string}){return rows.length?<div className="mini-list">{rows.map(r=><div key={r.id}><b>{String(r[name]||'—')}</b><span>{String(r.customer||r.supplier||'—')}</span><em>{String(r.status||'—')}</em></div>)}</div>:<div className="mini-empty"><BarChart3/><span>لا توجد بيانات مسجلة</span></div>}
