import { useState } from 'react';
import { Plus, CheckCircle2 } from 'lucide-react';
import { Button, Card, PageHead, Sheet, Tabs } from './components';
import { money, uid } from './store';
import type { Column, Row } from './types';
import type { ERPContext } from './advanced';
const n=(v:unknown)=>Number(v)||0;
const total=(rows:Record<string,Row[]>,key:string,id:string)=>(rows[key]||[]).filter(x=>x.parentId===id).reduce((s,x)=>s+n(x.quantity)*n(x.price),0);

function RecipeLines({ctx,parentId}:{ctx:ERPContext;parentId:string}){const key='productMaterials',items=(ctx.rows[key]||[]).filter(x=>x.parentId===parentId),stock=['wood','iron','paint','accessories','aluminum'].flatMap(k=>ctx.rows[k]||[]);const cols:Column[]=[{key:'item',label:'المادة الخام',type:'select',options:stock.map(x=>String(x.name))},{key:'quantity',label:'الكمية',type:'number'},{key:'unit',label:'الوحدة',type:'select',options:['متر مكعب','متر','كجم','جم','قطعة','لتر','جالون']},{key:'length',label:'الطول',type:'number'},{key:'width',label:'العرض',type:'number'},{key:'thickness',label:'التخانة',type:'number'},{key:'priceMode',label:'السعر المستخدم',type:'select',options:['سعر الشراء','سعر البيع']},{key:'price',label:'سعر الوحدة',type:'number'},{key:'cost',label:'التكلفة',calc:r=>money(n(r.quantity)*n(r.price))}];const save=(v:Row[])=>ctx.setRows({...ctx.rows,[key]:[...(ctx.rows[key]||[]).filter(x=>x.parentId!==parentId),...v]});return <Sheet columns={cols} rows={items} onChange={v=>save(v.map(line=>{const source=stock.find(x=>x.name===line.item);return source&&line.item!==items.find(x=>x.id===line.id)?.item?{...line,unit:source.unit||line.unit,price:line.priceMode==='سعر البيع'?n(source.sell):n(source.buy)}:line}))} onAdd={()=>save([...items,{id:uid(),parentId,quantity:1,priceMode:'سعر الشراء'}])} addLabel="إضافة مادة خام" onDelete={id=>save(items.filter(x=>x.id!==id))}/>}

export function AdvancedProducts(ctx:ERPContext){const [filter,setFilter]=useState('كل الأنواع'),all=ctx.rows.products||[],visible=all.filter(x=>filter==='كل الأنواع'||x.kind===filter);const cols:Column[]=[{key:'name',label:'اسم المنتج'},{key:'kind',label:'النوع',type:'select',options:['منتج نهائي جاهز','منتج تصنيعي','مادة خام']},{key:'sale',label:'سعر البيع',type:'number'},{key:'unit',label:'الوحدة',type:'select',options:['قطعة','متر','متر مكعب','كجم','لتر','طقم']},{key:'stock',label:'الرصيد',type:'number'},{key:'image',label:'الصورة',type:'readonly'},{key:'cost',label:'تكلفة التصنيع',calc:r=>r.kind==='منتج تصنيعي'?money(total(ctx.rows,'productMaterials',r.id)+n(r.labor)):'—'},{key:'final',label:'السعر النهائي',calc:r=>money(r.priceMode==='تلقائي'?total(ctx.rows,'productMaterials',r.id)+n(r.labor):n(r.sale))}];const update=(shown:Row[])=>ctx.setRows({...ctx.rows,products:all.map(r=>shown.find(x=>x.id===r.id)||r)});return <><PageHead title="المنتجات والخدمات" desc="وصفات الخامات وتكلفة العمالة والتسعير التلقائي" action={<Button onClick={()=>ctx.setRows({...ctx.rows,products:[{id:uid(),kind:'منتج نهائي جاهز',unit:'قطعة',stock:0,priceMode:'يدوي'},...all]})}><Plus/>إضافة منتج</Button>}/><div className="filter-row"><span>{visible.length} منتج</span><select value={filter} onChange={e=>setFilter(e.target.value)}>{['كل الأنواع','منتج نهائي جاهز','منتج تصنيعي','مادة خام'].map(x=><option key={x}>{x}</option>)}</select></div><Sheet columns={cols} rows={visible} onChange={update} onDelete={id=>ctx.setRows({...ctx.rows,products:all.filter(x=>x.id!==id)})} expanded={r=>r.kind==='منتج تصنيعي'?<div><RecipeLines ctx={ctx} parentId={r.id}/><div className="cost-controls"><label>تكلفة العمالة<input type="number" value={n(r.labor)} onChange={e=>update([{...r,labor:n(e.target.value)}])}/></label><label>طريقة السعر<select value={String(r.priceMode||'تلقائي')} onChange={e=>update([{...r,priceMode:e.target.value}])}><option>تلقائي</option><option>يدوي</option></select></label><div><span>إجمالي المواد</span><b>{money(total(ctx.rows,'productMaterials',r.id))}</b></div><div><span>التكلفة النهائية</span><b>{money(total(ctx.rows,'productMaterials',r.id)+n(r.labor))}</b></div></div></div>:<div className="details-note">لا توجد وصفة تصنيع لهذا النوع.</div>}/></>}

export function AdvancedPayroll(ctx:ERPContext){const [tab,setTab]=useState('يومية'),[month,setMonth]=useState(new Date().toISOString().slice(0,7)),key=tab==='يومية'?'daily':tab==='إنتاج'?'piece':'employees';const daily:Column[]=[{key:'name',label:'اسم العامل'},{key:'day',label:'اليوم',type:'date'},{key:'wage',label:'الأجر اليومي',type:'number'},{key:'days',label:'عدد الأيام',type:'number'},{key:'total',label:'الإجمالي',calc:r=>money(n(r.wage)*n(r.days))},{key:'paid',label:'الصرف',type:'status',options:['مستحق','تم الصرف']}],piece:Column[]=[{key:'name',label:'اسم الصنايعي'},{key:'order',label:'أمر التصنيع / المنتج'},{key:'count',label:'عدد القطع',type:'number'},{key:'price',label:'سعر القطعة',type:'number'},{key:'total',label:'الإجمالي',calc:r=>money(n(r.count)*n(r.price))},{key:'paid',label:'الصرف',type:'status',options:['مستحق','تم الصرف']}],employees:Column[]=[{key:'name',label:'الاسم'},{key:'job',label:'الوظيفة'},{key:'salary',label:'الأساسي',type:'number'},{key:'phone',label:'الهاتف'},{key:'hire',label:'تاريخ التعيين',type:'date'},{key:'bonus',label:'الحوافز',type:'number'},{key:'deduction',label:'الخصومات',type:'number'},{key:'net',label:'الصافي',calc:r=>money(n(r.salary)+n(r.bonus)-n(r.deduction))},{key:'paid',label:'الصرف',type:'status',options:['مستحق','تم الصرف']}];const save=(next:Row[])=>{let rows={...ctx.rows,[key]:next};for(const r of next){const old=(ctx.rows[key]||[]).find(x=>x.id===r.id);if(r.paid==='تم الصرف'&&old?.paid!=='تم الصرف'){const amount=tab==='يومية'?n(r.wage)*n(r.days):tab==='إنتاج'?n(r.count)*n(r.price):n(r.salary)+n(r.bonus)-n(r.deduction);rows.journal=[{id:uid(),date:new Date().toISOString().slice(0,10),type:'صرف راتب',description:`صرف ${tab} - ${r.name}`,amount,side:'مدين',locked:true},...(rows.journal||[])]}}ctx.setRows(rows)};const payAll=()=>save((ctx.rows.employees||[]).map(x=>({...x,paid:'تم الصرف',payMonth:month})));return <><PageHead title="الرواتب" desc="صرف اليومية والإنتاج والشهرية مع قيد مالي تلقائي" action={<div className="head-actions">{tab==='شهرية'&&<Button variant="outline" onClick={payAll}>صرف الكل</Button>}<Button onClick={()=>ctx.setRows({...ctx.rows,[key]:[{id:uid(),paid:'مستحق'},...(ctx.rows[key]||[])]})}><Plus/>إضافة سجل</Button></div>}/><Card className="automation-note"><CheckCircle2/><div><b>كل عملية صرف تُسجل تلقائياً في القيود اليومية</b><span>غيّر حالة الصف إلى «تم الصرف» لتنفيذ الحركة</span></div></Card><Tabs items={['يومية','إنتاج','شهرية']} active={tab} onChange={setTab}/>{tab==='شهرية'&&<Card className="month-bar"><label>الشهر<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label></Card>}<Sheet columns={tab==='يومية'?daily:tab==='إنتاج'?piece:employees} rows={ctx.rows[key]||[]} onChange={save} onDelete={id=>ctx.setRows({...ctx.rows,[key]:(ctx.rows[key]||[]).filter(x=>x.id!==id)})}/></>}
