import { useState } from 'react';
import { LayoutDashboard,Package,Warehouse,Users,Truck,WalletCards,Factory,ShoppingCart,Receipt,ClipboardList,Trash2,RotateCcw,BookOpen,BarChart3,Bell,Menu,PanelRightClose,CircleDollarSign,Clock3,TrendingUp,Boxes,Plus } from 'lucide-react';
import { Badge,Button,Card,PageHead,PrintButton,Sheet,Tabs } from './components';
import { money,uid,useLocalState } from './store';
import type { Column,Row,Section } from './types';

const navigation:{id:Section;label:string;icon:any}[]=[
 ['dashboard','لوحة التحكم',LayoutDashboard],['products','المنتجات والخدمات',Package],['inventory','المخزن',Warehouse],['customers','العملاء',Users],['suppliers','الموردون',Truck],['payroll','الرواتب',WalletCards],['manufacturing','أوامر التصنيع',Factory],['purchases','أوامر الشراء',ShoppingCart],['sales','فواتير البيع',Receipt],['purchaseInvoices','فواتير الشراء',ClipboardList],['waste','التوالف',Trash2],['surplus','زيادات الأوردرات',RotateCcw],['journal','القيود اليومية',BookOpen],['reports','التقارير',BarChart3]
].map(([id,label,icon])=>({id:id as Section,label:label as string,icon}));

const initial:Record<string,Row[]>={
 products:[{id:'p1',name:'كرسي سفرة',kind:'منتج تصنيعي',unit:'قطعة',sale:1850,materials:970,labor:350},{id:'p2',name:'خشب زان',kind:'مادة خام',unit:'متر مكعب',sale:0},{id:'p3',name:'طاولة جانبية',kind:'منتج نهائي جاهز',unit:'قطعة',sale:2200}],
 wood:[{id:'w1',name:'خشب زان',count:12,length:220,width:18,thickness:4,buy:28500,sell:32000}],iron:[],paint:[{id:'pa1',name:'دهان لاكيه',kind:'دهان',count:4,size:3,unit:'لتر',buy:520,sell:650}],accessories:[],aluminum:[],workshop:[],customers:[],suppliers:[],daily:[],piece:[],employees:[],manufacturing:[],purchases:[],sales:[],purchaseInvoices:[],waste:[],surplus:[],journal:[]
};
type Ctx={rows:Record<string,Row[]>;setRows:(x:Record<string,Row[]>)=>void;go:(s:Section)=>void};
const options=(...x:string[])=>x;
const calc=(key:string,fn:(r:Row)=>string|number,label:string):Column=>({key,label,calc:fn});

export default function App(){const [section,setSection]=useState<Section>('dashboard');const [open,setOpen]=useState(true);const [rows,setRows]=useLocalState('elayad-data',initial);return <div className="app" dir="rtl"><aside className={open?'sidebar':'sidebar collapsed'}><div className="brand"><div className="brand-mark"><Factory/></div><div><strong>El Ayad</strong><small>Furniture ERP</small></div><button className="collapse" onClick={()=>setOpen(!open)}><PanelRightClose/></button></div><nav>{navigation.map(n=><button key={n.id} className={section===n.id?'active':''} onClick={()=>setSection(n.id)}><n.icon/><span>{n.label}</span></button>)}</nav><div className="sidebar-foot"><div className="avatar">EA</div><div><b>إدارة النظام</b><small>الحفظ التلقائي مفعّل</small></div></div></aside><main className={open?'main':'main wide'}><header><div className="header-title"><button className="mobile-menu" onClick={()=>setOpen(!open)}><Menu/></button><div><b>El Ayad Furniture</b><span>نظام إدارة المعرض والورشة</span></div></div><div className="header-actions"><button className="notify"><Bell/><i/></button><div className="avatar">EA</div></div></header><div className="content"><SectionView section={section} rows={rows} setRows={setRows} go={setSection}/></div></main></div>}

function SectionView({section,...ctx}:Ctx&{section:Section}){if(section==='dashboard')return <Dashboard {...ctx}/>;if(section==='products')return <Products {...ctx}/>;if(section==='inventory')return <Inventory {...ctx}/>;if(section==='customers')return <People kind="customers" {...ctx}/>;if(section==='suppliers')return <People kind="suppliers" {...ctx}/>;if(section==='payroll')return <Payroll {...ctx}/>;if(section==='manufacturing')return <Orders kind="manufacturing" {...ctx}/>;if(section==='purchases')return <Orders kind="purchases" {...ctx}/>;if(section==='sales')return <Invoices kind="sales" {...ctx}/>;if(section==='purchaseInvoices')return <Invoices kind="purchaseInvoices" {...ctx}/>;if(section==='waste')return <Waste {...ctx}/>;if(section==='surplus')return <Surplus {...ctx}/>;if(section==='journal')return <Journal {...ctx}/>;return <Reports {...ctx}/>}
function actions(ctx:Ctx,key:string){return {update:(v:Row[])=>ctx.setRows({...ctx.rows,[key]:v}),add:(extra:Partial<Row>={})=>ctx.setRows({...ctx.rows,[key]:[{id:uid(),...extra},...ctx.rows[key]]}),del:(id:string)=>ctx.setRows({...ctx.rows,[key]:ctx.rows[key].filter(r=>r.id!==id)})}}

function Dashboard({rows,go}:Ctx){const cards=[['مبيعات اليوم',money(0),CircleDollarSign,'green'],['أوامر تصنيع مفتوحة',rows.manufacturing.filter(r=>r.status!=='مكتمل').length,Factory,'blue'],['مواعيد تسليم متأخرة',0,Clock3,'red'],['المبلغ في الخزنة',money(0),WalletCards,'purple'],['أرباح الشهر',money(0),TrendingUp,'amber']];return <><div className="dash-title"><div><span className="eyebrow">نظرة عامة</span><h1>أهلاً بك في <span>El Ayad Furniture</span></h1><p>تابع أداء المعرض والورشة من مكان واحد.</p></div><div className="today">الخميس، ٢ يوليو ٢٠٢٦</div></div><div className="stats">{cards.map(([l,v,I,t]:any)=><Card className="stat" key={l}><div className={`stat-icon ${t}`}><I/></div><div><span>{l}</span><strong>{v}</strong><small><TrendingUp/> يتم التحديث تلقائياً</small></div></Card>)}</div><div className="dash-grid"><Card className="chart-card"><Title title="المبيعات الشهرية" sub="إجمالي المبيعات خلال آخر 6 أشهر"/><div className="chart css-chart">{['يناير','فبراير','مارس','أبريل','مايو','يونيو'].map((m,i)=><div key={m}><span className="bar" style={{height:`${8+i*4}%`}}/><small>{m}</small></div>)}</div></Card><Card className="alerts"><Title title="تنبيهات سريعة" sub="عناصر تحتاج إلى انتباهك"/><div className="all-good"><div><Bell/></div><b>كل شيء على ما يرام</b><span>لا توجد تنبيهات عاجلة حالياً</span></div></Card></div><div className="dash-grid bottom"><Card><Title title="آخر فواتير البيع" sub="أحدث الحركات المسجلة"/><Empty/></Card><Card><Title title="أوامر التصنيع الأخيرة" sub="متابعة حالة الإنتاج"/><Empty/></Card></div></>}
const Title=({title,sub}:{title:string;sub:string})=><div className="card-title"><div><h3>{title}</h3><p>{sub}</p></div></div>;
const Empty=()=> <div className="mini-empty"><ClipboardList/><span>لا توجد حركات مسجلة بعد</span></div>;

function Products(ctx:Ctx){const a=actions(ctx,'products');const columns:Column[]=[{key:'name',label:'اسم المنتج',width:190},{key:'kind',label:'النوع',type:'select',options:options('منتج نهائي جاهز','منتج تصنيعي','مادة خام'),width:170},{key:'sale',label:'سعر البيع',type:'number'},{key:'unit',label:'الوحدة',type:'select',options:options('قطعة','متر','متر مكعب','كجم','لتر','طقم')},calc('cost',r=>r.kind==='منتج تصنيعي'?money(Number(r.materials)+Number(r.labor)):'—','تكلفة التصنيع')];return <><PageHead title="المنتجات والخدمات" desc="إدارة المنتجات الجاهزة والتصنيعية والمواد الخام" action={<Button onClick={()=>a.add({kind:'منتج نهائي جاهز',unit:'قطعة'})}><Plus/>إضافة منتج</Button>}/><div className="filter-row"><div className="summary-pill"><Boxes/> {ctx.rows.products.length} منتج</div><select><option>كل الأنواع</option></select></div><Sheet columns={columns} rows={ctx.rows.products} onChange={a.update} onDelete={a.del} expanded={r=><Recipe row={r} ctx={ctx}/>}/></>}
function Recipe({row,ctx}:{row:Row;ctx:Ctx}){if(row.kind!=='منتج تصنيعي')return <div className="details-note"><Package/>يمكن تعديل بيانات المنتج مباشرة من الصف.</div>;const edit=(p:Partial<Row>)=>actions(ctx,'products').update(ctx.rows.products.map(x=>x.id===row.id?{...x,...p}:x));return <div className="recipe"><div className="recipe-head"><div><b>مكونات التصنيع</b><span>تُحتسب التكلفة فوراً</span></div><Button variant="outline"><Plus/>إضافة مادة خام</Button></div><div className="material-grid"><label>المادة الخام<select>{ctx.rows.products.filter(x=>x.kind==='مادة خام').map(x=><option key={x.id}>{String(x.name)}</option>)}</select></label><label>الكمية<input type="number" defaultValue="1"/></label><label>نظام السعر<select><option>سعر الشراء</option><option>سعر البيع</option></select></label><label>تكلفة المواد<input type="number" value={Number(row.materials||0)} onChange={e=>edit({materials:Number(e.target.value)})}/></label><label>تكلفة العمالة<input type="number" value={Number(row.labor||0)} onChange={e=>edit({labor:Number(e.target.value)})}/></label><div className="recipe-total"><span>السعر النهائي</span><strong>{money(Number(row.materials)+Number(row.labor))}</strong></div></div></div>}

const metal:Column[]=[{key:'name',label:'اسم المنتج'},{key:'kind',label:'النوع',type:'select',options:options('لوح','ماسورة','علب','بيضاوي','سلك لحام','سيخ')},{key:'count',label:'العدد',type:'number'},{key:'length',label:'الطول (م)',type:'number'},{key:'width',label:'العرض',type:'number'},{key:'buy',label:'سعر الشراء',type:'number'},{key:'sell',label:'سعر البيع',type:'number'},calc('total',r=>money(Number(r.count)*Number(r.length||1)*Number(r.buy)),'الإجمالي')];
function Inventory(ctx:Ctx){const [tab,setTab]=useState('الخشب');const map:Record<string,{key:string;cols:Column[]}>={الخشب:{key:'wood',cols:[{key:'name',label:'نوع الخشب'},{key:'count',label:'العدد',type:'number'},{key:'length',label:'الطول (سم)',type:'number'},{key:'width',label:'العرض (سم)',type:'number'},{key:'thickness',label:'التخانة (سم)',type:'number'},calc('cube',r=>(Number(r.length)*Number(r.width)*Number(r.thickness)/1e6).toFixed(4),'تكعيب القطعة'),{key:'buy',label:'سعر شراء المتر',type:'number'},{key:'sell',label:'سعر بيع المتر',type:'number'},calc('total',r=>money(Number(r.count)*Number(r.length)*Number(r.width)*Number(r.thickness)/1e6*Number(r.buy)),'إجمالي الشراء')]},الحديد:{key:'iron',cols:metal},الدهانات:{key:'paint',cols:[{key:'name',label:'اسم المنتج'},{key:'kind',label:'النوع',type:'select',options:options('دهان','تنر','زيت','غراء','منعم أقمشة','عازل')},{key:'color',label:'اللون'},{key:'count',label:'العدد',type:'number'},{key:'size',label:'حجم العبوة',type:'number'},{key:'unit',label:'الوحدة',type:'select',options:options('لتر','جالون','كجم','جم')},{key:'buy',label:'سعر الشراء',type:'number'},{key:'sell',label:'سعر البيع',type:'number'},calc('total',r=>money(Number(r.count)*Number(r.buy)),'الإجمالي')]},الإكسسوارات:{key:'accessories',cols:stockCols()},الألومنيوم:{key:'aluminum',cols:metal},'مستلزمات الورشة':{key:'workshop',cols:stockCols()}};const cf=map[tab],a=actions(ctx,cf.key);return <><PageHead title="المخزن" desc="إدارة المواد الخام والكميات والأسعار بأنظمة قياس ديناميكية" action={<Button variant="outline"><Plus/>إضافة قسم جديد</Button>}/><Tabs items={Object.keys(map)} active={tab} onChange={setTab}/><div className="inventory-summary"><div><Boxes/><span>إجمالي قيمة القسم</span><strong>{money(ctx.rows[cf.key].reduce((s,r)=>s+Number(r.count||r.quantity)*Number(r.buy),0))}</strong></div><div><Package/><span>عدد الأصناف</span><strong>{ctx.rows[cf.key].length}</strong></div></div><Sheet columns={cf.cols} rows={ctx.rows[cf.key]} onChange={a.update} onAdd={()=>a.add()} addLabel="إضافة صنف" onDelete={a.del}/></>}
function stockCols():Column[]{return [{key:'name',label:'اسم الصنف'},{key:'quantity',label:'الكمية',type:'number'},{key:'buy',label:'سعر الشراء',type:'number'},{key:'sell',label:'سعر البيع',type:'number'},calc('tb',r=>money(Number(r.quantity)*Number(r.buy)),'إجمالي الشراء'),calc('ts',r=>money(Number(r.quantity)*Number(r.sell)),'إجمالي البيع')]}

function People({kind,...ctx}:Ctx&{kind:'customers'|'suppliers'}){const a=actions(ctx,kind),customer=kind==='customers';const columns:Column[]=customer?[{key:'name',label:'الاسم الكامل',width:180},{key:'phone',label:'الهاتف'},{key:'phone2',label:'هاتف إضافي'},{key:'address',label:'العنوان'},{key:'city',label:'المدينة',type:'select',options:options('القاهرة','الجيزة','الإسكندرية','القليوبية','الشرقية','الدقهلية','الغربية')},{key:'credit',label:'حد الائتمان',type:'number'},calc('balance',r=>money(r.balance as number),'الرصيد'),calc('total',r=>money(r.total as number),'إجمالي المشتريات')]:[{key:'name',label:'اسم المورد'},{key:'contact',label:'جهة الاتصال'},{key:'phone',label:'الهاتف'},{key:'city',label:'المدينة'},{key:'materials',label:'المواد الموردة',type:'select',options:options('خشب','حديد','دهانات','ألومنيوم','إكسسوارات','مستلزمات ورشة','أخرى')},calc('balance',r=>money(r.balance as number),'الرصيد')];return <><PageHead title={customer?'العملاء':'الموردون'} desc="إدارة البيانات والأرصدة وسجل التعاملات" action={<Button onClick={()=>a.add()}><Plus/>إضافة {customer?'عميل':'مورد'}</Button>}/><Sheet columns={columns} rows={ctx.rows[kind]} onChange={a.update} onDelete={a.del} expanded={()=> <div className="history-grid">{['الرصيد الحالي','إجمالي التعاملات','الفواتير','المدفوعات'].map(x=><div key={x}><span>{x}</span><b>{money(0)}</b></div>)}</div>}/></>}

function Payroll(ctx:Ctx){const [tab,setTab]=useState('يومية'),key=tab==='يومية'?'daily':tab==='إنتاج'?'piece':'employees',a=actions(ctx,key);const columns:Column[]=tab==='يومية'?[{key:'name',label:'اسم العامل'},{key:'day',label:'اليوم',type:'date'},{key:'wage',label:'الأجر اليومي',type:'number'},{key:'days',label:'عدد الأيام',type:'number'},calc('total',r=>money(Number(r.wage)*Number(r.days)),'الإجمالي'),{key:'paid',label:'الحالة',type:'status',options:options('مستحق','تم الصرف')}]:tab==='إنتاج'?[{key:'name',label:'اسم الصنايعي'},{key:'order',label:'أمر التصنيع / المنتج'},{key:'count',label:'عدد القطع',type:'number'},{key:'price',label:'سعر القطعة',type:'number'},calc('total',r=>money(Number(r.count)*Number(r.price)),'الإجمالي'),{key:'paid',label:'الحالة',type:'status',options:options('مستحق','تم الصرف')}]:[{key:'name',label:'اسم الموظف'},{key:'job',label:'الوظيفة'},{key:'salary',label:'الراتب الأساسي',type:'number'},{key:'phone',label:'الهاتف'},{key:'hire',label:'تاريخ التعيين',type:'date'}];return <><PageHead title="الرواتب" desc="الأجور اليومية ورواتب الإنتاج والموظفين" action={<Button onClick={()=>a.add()}><Plus/>إضافة سجل</Button>}/><Tabs items={options('يومية','إنتاج','شهرية')} active={tab} onChange={setTab}/><Sheet columns={columns} rows={ctx.rows[key]} onChange={a.update} onDelete={a.del}/></>}

function Orders({kind,...ctx}:Ctx&{kind:'manufacturing'|'purchases'}){const a=actions(ctx,kind),m=kind==='manufacturing';const columns:Column[]=m?[{key:'number',label:'رقم الأمر'},{key:'customer',label:'العميل'},{key:'product',label:'المنتج'},{key:'quantity',label:'الكمية',type:'number'},{key:'cost',label:'تكلفة التصنيع',type:'number'},{key:'profit',label:'المكسب',type:'number'},calc('final',r=>money(Number(r.cost)*Number(r.quantity||1)+Number(r.profit)),'السعر النهائي'),{key:'delivery',label:'تاريخ التسليم',type:'date'},{key:'status',label:'الحالة',type:'status',options:options('قيد التصنيع','مكتمل')}]:[{key:'number',label:'رقم الأمر'},{key:'supplier',label:'المورد'},{key:'date',label:'تاريخ الطلب',type:'date'},{key:'receive',label:'الاستلام المتوقع',type:'date'},{key:'quantity',label:'الكمية',type:'number'},{key:'price',label:'سعر الوحدة',type:'number'},calc('total',r=>money(Number(r.quantity)*Number(r.price)),'الإجمالي'),{key:'status',label:'الحالة',type:'status',options:options('قيد الطلب','تم الاستلام')}];return <><PageHead title={m?'أوامر التصنيع':'أوامر الشراء'} desc={m?'تخطيط ومتابعة مراحل التصنيع والتسليم':'إدارة طلبات الموردين واستلام المخزون'} action={<Button onClick={()=>a.add({number:`${m?'MO':'PO'}-${String(ctx.rows[kind].length+1).padStart(4,'0')}`,status:m?'قيد التصنيع':'قيد الطلب'})}><Plus/>إضافة أمر</Button>}/><Sheet columns={columns} rows={ctx.rows[kind]} onChange={a.update} onDelete={a.del} expanded={r=><div className="order-detail"><div><span>تفاصيل البنود والمواد</span><b>أضف البيانات مباشرة داخل الخلايا</b></div><strong>{money(Number(r.quantity)*Number(r.price||r.cost))}</strong></div>}/></>}

function Invoices({kind,...ctx}:Ctx&{kind:'sales'|'purchaseInvoices'}){const a=actions(ctx,kind),sale=kind==='sales';const columns:Column[]=[{key:'number',label:'رقم الفاتورة'},{key:sale?'customer':'supplier',label:sale?'العميل':'المورد'},{key:'date',label:'التاريخ',type:'date'},{key:'product',label:'المنتج / المادة'},{key:'quantity',label:'الكمية',type:'number'},{key:'price',label:'سعر الوحدة',type:'number'},...(sale?[{key:'discount',label:'الخصم',type:'number' as const},{key:'payment',label:'طريقة الدفع',type:'select' as const,options:options('كاش','تقسيط','تحويل')}]:[]),calc('total',r=>money(Number(r.quantity)*Number(r.price)-Number(r.discount||0)),'الإجمالي النهائي')];return <><PageHead title={sale?'فواتير البيع':'فواتير الشراء'} desc="الفواتير المباشرة والمتولدة تلقائياً من الأوامر" action={<div className="head-actions"><PrintButton/><Button onClick={()=>a.add({number:`${sale?'SI':'PI'}-${String(ctx.rows[kind].length+1).padStart(4,'0')}`,date:new Date().toISOString().slice(0,10)})}><Plus/>إنشاء فاتورة</Button></div>}/><Sheet columns={columns} rows={ctx.rows[kind]} onChange={a.update} onDelete={a.del} expanded={r=><div className="invoice-preview"><div className="brand-mark"><Factory/></div><h3>El Ayad Furniture</h3><span>فاتورة رقم {String(r.number||'—')}</span><strong>{money(Number(r.quantity)*Number(r.price)-Number(r.discount||0))}</strong><PrintButton/></div>}/></>}

function Waste(ctx:Ctx){const a=actions(ctx,'waste');const c:Column[]=[{key:'item',label:'المنتج / المادة'},{key:'quantity',label:'الكمية',type:'number'},{key:'price',label:'السعر',type:'number'},{key:'reason',label:'سبب التلف',type:'select',options:options('كسر','عيب صناعة','تخزين','رطوبة','أخرى')},{key:'date',label:'التاريخ',type:'date'},calc('loss',r=>money(Number(r.quantity)*Number(r.price)),'الخسارة')];return <Basic title="التوالف" desc="تسجيل الخامات التالفة واحتساب خسائرها" label="إضافة تالف" rows={ctx.rows.waste} cols={c} a={a}/>}
function Surplus(ctx:Ctx){const a=actions(ctx,'surplus');const c:Column[]=[{key:'order',label:'أمر التصنيع'},{key:'material',label:'المادة'},{key:'quantity',label:'الكمية',type:'number'},{key:'dimensions',label:'المقاسات'},{key:'usable',label:'صالح للاستخدام؟',type:'select',options:options('نعم','لا')},calc('status',r=>r.usable==='نعم'?'راجع للمخزن':r.usable==='لا'?'محوّل للتوالف':'بانتظار التحديد','الإجراء')];return <Basic title="زيادات الأوردرات" desc="إعادة الخامات المتبقية للمخزن أو تحويلها إلى التوالف" label="إضافة زيادة" rows={ctx.rows.surplus} cols={c} a={a}/>}
function Basic({title,desc,label,rows,cols,a}:{title:string;desc:string;label:string;rows:Row[];cols:Column[];a:ReturnType<typeof actions>}){return <><PageHead title={title} desc={desc} action={<Button onClick={()=>a.add()}><Plus/>{label}</Button>}/><Sheet columns={cols} rows={rows} onChange={a.update} onDelete={a.del}/></>}
function Journal(ctx:Ctx){const a=actions(ctx,'journal');const c:Column[]=[{key:'date',label:'التاريخ',type:'date'},{key:'type',label:'النوع',type:'select',options:options('مصروفات','سداد عميل','سداد لمورد','فاتورة بيع','فاتورة شراء','مرتجع بيع','صرف راتب','تالف')},{key:'description',label:'البيان',width:220},{key:'party',label:'العميل / المورد'},{key:'payment',label:'طريقة الدفع',type:'select',options:options('كاش','تحويل','آجل')},{key:'amount',label:'المبلغ',type:'number'},{key:'side',label:'مدين / دائن',type:'select',options:options('مدين','دائن')}];return <><PageHead title="القيود اليومية" desc="دفتر الحركة المالية والقيود اليدوية والتلقائية" action={<Button onClick={()=>a.add({date:new Date().toISOString().slice(0,10)})}><Plus/>إضافة قيد يدوي</Button>}/><div className="journal-balance"><span>إجمالي المدين <b>{money(ctx.rows.journal.filter(x=>x.side==='مدين').reduce((s,x)=>s+Number(x.amount),0))}</b></span><span>إجمالي الدائن <b>{money(ctx.rows.journal.filter(x=>x.side==='دائن').reduce((s,x)=>s+Number(x.amount),0))}</b></span></div><Sheet columns={c} rows={ctx.rows.journal} onChange={a.update} onDelete={a.del}/></>}
function Reports(ctx:Ctx){const [tab,setTab]=useState('المبيعات'),sales=ctx.rows.sales.reduce((s,r)=>s+Number(r.quantity)*Number(r.price)-Number(r.discount||0),0),buy=ctx.rows.purchaseInvoices.reduce((s,r)=>s+Number(r.quantity)*Number(r.price),0),waste=ctx.rows.waste.reduce((s,r)=>s+Number(r.quantity)*Number(r.price),0);return <><PageHead title="التقارير" desc="تحليلات مالية وتشغيلية لحظية من بيانات النظام" action={<PrintButton/>}/><Tabs items={options('المبيعات','المشتريات','المخزن','الأرباح والخسائر','العملاء','الموظفون والرواتب','أوامر التصنيع','التقرير الشامل')} active={tab} onChange={setTab}/><Card className="report-filter"><label>من تاريخ<input type="date"/></label><label>إلى تاريخ<input type="date"/></label><label>الفترة<select><option>هذا الشهر</option><option>هذا العام</option></select></label><Button>تطبيق الفلتر</Button></Card><div className="report-hero"><div><span>صافي النتيجة</span><strong>{money(sales-buy-waste)}</strong><small>يُحتسب تلقائياً من الحركات المسجلة</small></div><BarChart3/></div><div className="report-cards">{[['المبيعات',sales],['المشتريات',buy],['المصروفات والتوالف',waste],['صافي الربح',sales-buy-waste]].map(([x,n]:any)=><Card key={x}><span>{x}</span><strong className={n<0?'negative':''}>{money(n)}</strong><div className="progress"><i style={{width:n?'65%':'0%'}}/></div></Card>)}</div><Card className="report-empty"><BarChart3/><h3>تفاصيل تقرير {tab}</h3><p>ستظهر التفاصيل تلقائياً عند تسجيل الحركات في الأقسام المرتبطة.</p></Card></>}
