import React, { useMemo, useState } from 'react';
import { Search, Plus, Trash2, ChevronDown, ChevronUp, ChevronsUpDown, Printer, MoreHorizontal } from 'lucide-react';
import type { Column, Row } from './types';

export const Button=({children,className='',variant='primary',...p}:React.ButtonHTMLAttributes<HTMLButtonElement>&{variant?:'primary'|'ghost'|'outline'|'danger'})=><button className={`btn ${variant} ${className}`} {...p}>{children}</button>;
export const Badge=({children,tone='neutral'}:{children:React.ReactNode;tone?:string})=><span className={`badge ${tone}`}>{children}</span>;
export const Card=({children,className=''}:{children:React.ReactNode;className?:string})=><section className={`card ${className}`}>{children}</section>;
export const PageHead=({title,desc,action}:{title:string;desc:string;action?:React.ReactNode})=><div className="page-head"><div><h1>{title}</h1><p>{desc}</p></div>{action}</div>;
export const Tabs=({items,active,onChange}:{items:string[];active:string;onChange:(x:string)=>void})=><div className="tabs">{items.map(x=><button key={x} className={active===x?'active':''} onClick={()=>onChange(x)}>{x}</button>)}</div>;

export function Sheet({columns,rows,onChange,onAdd,onDelete,addLabel='إضافة صف',expanded}:{columns:Column[];rows:Row[];onChange:(r:Row[])=>void;onAdd?:()=>void;onDelete?:(id:string)=>void;addLabel?:string;expanded?:(r:Row)=>React.ReactNode}){
 const [query,setQuery]=useState(''); const [sort,setSort]=useState(''); const [asc,setAsc]=useState(true); const [open,setOpen]=useState<string>(); const [page,setPage]=useState(1); const pageSize=8;
 const shown=useMemo(()=>{let x=rows.filter(r=>Object.values(r).some(v=>String(v??'').toLowerCase().includes(query.toLowerCase())));if(sort)x=[...x].sort((a,b)=>String(a[sort]??'').localeCompare(String(b[sort]??''),'ar',{numeric:true})*(asc?1:-1));return x},[rows,query,sort,asc]);
 const edit=(id:string,key:string,value:string)=>onChange(rows.map(r=>r.id===id?{...r,[key]:columns.find(c=>c.key===key)?.type==='number'?Number(value):value}:r));
 return <Card className="sheet-card"><div className="sheet-tools"><div className="search"><Search size={17}/><input placeholder="بحث في الجدول..." value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}}/></div><div className="tool-actions"><span className="saved"><i/> حفظ تلقائي</span>{onAdd&&<Button onClick={onAdd}><Plus size={17}/>{addLabel}</Button>}</div></div><div className="table-wrap"><table className="sheet"><thead><tr>{expanded&&<th/>}{columns.map(c=><th key={c.key} style={{minWidth:c.width}} onClick={()=>{if(sort===c.key)setAsc(!asc);else{setSort(c.key);setAsc(true)}}}>{c.label}<ChevronsUpDown size={13}/></th>)}{onDelete&&<th/>}</tr></thead><tbody>{shown.slice((page-1)*pageSize,page*pageSize).map(r=><React.Fragment key={r.id}><tr>{expanded&&<td><button className="icon" onClick={()=>setOpen(open===r.id?undefined:r.id)}>{open===r.id?<ChevronUp/>:<ChevronDown/>}</button></td>}{columns.map(c=><td key={c.key}>{c.calc?<span className="calc">{c.calc(r)}</span>:c.type==='select'||c.type==='status'?<select className="cell" value={String(r[c.key]??'')} onChange={e=>edit(r.id,c.key,e.target.value)}><option value="">—</option>{c.options?.map(o=><option key={o}>{o}</option>)}</select>:c.type==='readonly'?<span className="readonly">{String(r[c.key]??'—')}</span>:<input className="cell" type={c.type==='number'?'number':c.type==='date'?'date':'text'} value={String(r[c.key]??'')} onChange={e=>edit(r.id,c.key,e.target.value)} onKeyDown={e=>e.key==='Enter'&&(e.currentTarget.blur())}/>}</td>)}{onDelete&&<td><button className="icon danger-text" onClick={()=>confirm('هل تريد حذف هذا الصف؟')&&onDelete(r.id)}><Trash2 size={17}/></button></td>}</tr>{open===r.id&&expanded&&<tr className="expand-row"><td colSpan={columns.length+2}>{expanded(r)}</td></tr>}</React.Fragment>)}{!shown.length&&<tr><td colSpan={columns.length+2}><div className="empty">لا توجد بيانات بعد. أضف صفاً لبدء العمل.</div></td></tr>}</tbody></table></div><div className="pager"><span>عرض {shown.length?((page-1)*pageSize+1):0}–{Math.min(page*pageSize,shown.length)} من {shown.length}</span><div><Button variant="outline" disabled={page===1} onClick={()=>setPage(page-1)}>السابق</Button><b>{page}</b><Button variant="outline" disabled={page*pageSize>=shown.length} onClick={()=>setPage(page+1)}>التالي</Button></div></div></Card>
}
export const PrintButton=()=> <Button variant="outline" onClick={()=>window.print()}><Printer size={17}/>طباعة</Button>;
export const MenuButton=()=> <button className="icon"><MoreHorizontal/></button>;
